package puma.hope.librarian_users.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
@Entity
@Table(name = "friendship_user_to_user_link", schema = "librarian")
public class Friendship {

    public Friendship(Long userId, Long friendId) {
        this.userId = userId;
        this.friendId = friendId;
    }

    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Schema(name = "id", example = "1", description = "Friendship ID, generated by the DataBase")
    Long id;

    @Column(name = "user_id")
    Long userId;
    @Column(name = "friend_id")
    Long friendId;

}
